"""create column updated_at in table users

Revision ID: 7b672ec66799
Revises: 31ba5ae888e0
Create Date: 2024-06-25 21:46:01.648894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b672ec66799'
down_revision: Union[str, None] = '31ba5ae888e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_ap', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_ap')
    # ### end Alembic commands ###
